/* Edit project copy, images and video URLs here. Paths are relative for GitHub Pages.
   Videos currently use the existing portfolio host and load only when opened. */
window.PORTFOLIO_PROJECTS = [
 { id: 'pixel', title: 'Pixel Network', category: 'Campaign visuals / Motion graphics', filters: ['graphic','motion'], image: 'assets/project-pixel-network.jpg', alt: 'Colourful vector illustration of a driver in a landscape', description: 'A social motion campaign built around colourful vector illustration and kinetic typography. A visual identity carried through short, engaging animated stories.', tools: 'After Effects · Vector motion graphics · Kinetic typography', video: 'https://my-portfolio-e4rk.vercel.app/videos/pixel-network.mp4', external: 'https://www.playbook.com/s/macstorage/nNaouTCFLEnKxkHvocNfR3A1?assetToken=Q3hydrZgSK8FouiTb5JkaydJ', selected: true },
 { id: 'nestle', title: 'Nestle — a little energy', category: 'Commercial / Motion graphics', filters: ['graphic','motion'], image: 'assets/project-nestle.jpg', alt: 'Colourful illustrated food icons on a bright yellow background', description: 'A short commercial motion piece combining playful illustrated visuals, rhythmic editing, and sound design.', tools: 'After Effects · Premiere Pro · Motion design · Sound design', video: 'https://my-portfolio-e4rk.vercel.app/videos/nestle-motion.mp4', external: 'https://www.playbook.com/s/macstorage/xWwoCnQA7PLfvsk6nceexhqP?assetToken=cucgyqr7SMfYf4mxAZEetDzR', selected: true },
 { id: 'honeywell', title: 'Print Without Limits', category: 'Campaign creative / Digital design', filters: ['graphic'], image: 'assets/project-honeywell.png', alt: 'Honeywell Print Without Limits campaign on a desktop monitor', description: 'Campaign creative and a Webflow landing page for Honeywell. Hardware mockups, digital ads, and a cohesive visual direction bring the product campaign together.', tools: 'Webflow · Campaign creative · Hardware mockups · Digital ads', selected: true },
 { id: 'subify', title: 'Subify — simply explained', category: '2D & 3D / Explainer', filters: ['motion'], image: 'assets/project-subify.jpg', alt: 'Your Shop illustration from the Subify explainer', description: 'An animated product explainer that uses simple forms and bold colour to make application features and workflows easier to understand.', tools: 'After Effects · Figma · 2D motion graphics · 3D animation · Sound design', video: 'https://my-portfolio-e4rk.vercel.app/videos/subify-explainer.mp4', external: 'https://www.playbook.com/s/macstorage/R1CDtjFBi7EbCHPJXsduirhx?assetToken=UhzFTS63qnWGaCk9WDoe1Rmg', selected: true },
 { id: 'epson', title: 'Epson C8000', category: '3D modelling / Product animation', filters: ['3d'], image: 'assets/project-blender-c8000.png', alt: 'Close-up 3D render of an Epson C8000 printer', description: 'Hard-surface product modelling and animation in Blender, with studio lighting and detailed texturing to reveal the product’s form.', tools: 'Blender · Hard-surface modelling · Lighting · Texturing · Product animation', video: 'https://my-portfolio-e4rk.vercel.app/c8000u-web.mp4', external: 'https://www.playbook.com/s/macstorage/AAKgAAByJUrAN91dNWTw7aJH?assetToken=fEAqdcVwg8hMYYG3RWyR8bin', selected: true },
 { id: 'bauer', title: 'Bauer Vapor', category: '3D modelling / Product animation', filters: ['3d'], image: 'assets/project-bauer-skate.png', alt: 'Bauer Vapor inline skate rendered inside an arena', description: 'A 3D exploration of the Bauer Vapor inline skate. Detailed hard-surface modelling, layered materials, and arena lighting bring the product into focus.', tools: 'Blender · Hard-surface modelling · Shading · Product animation', video: 'https://my-portfolio-e4rk.vercel.app/skate-3d-animation-web.mp4', external: 'https://www.playbook.com/s/macstorage/vZhygRYsf2ip8xfv5QnpKUKp?assetToken=PQL7EUXa3esyMCS7GdASv924', selected: true },
 { id: 'reel', title: '3D product animation showreel', category: 'Selected motion / 01:15', image: 'assets/project-reel-3d.jpg', alt: '3D product animation showreel frame', description: 'A collection of 3D product animations, studio lighting, hard-surface modelling, and commercial product demonstrations.', tools: 'Blender · Cinema 4D · After Effects · Studio lighting', video: 'https://my-portfolio-e4rk.vercel.app/videos/reel-3d-product.mp4', external: 'https://www.playbook.com/s/macstorage/v5o557yrHNYKFSbEcqKWSXV1?assetToken=Z9pDifP7BXiA4rvQ6qeyTCEm' },
 { id: 'zebra', title: 'Zebra Technologies', category: 'Secondary discipline / Web design', image: 'assets/zebra-page.webp', alt: 'Full Zebra industrial hardware campaign landing page', description: 'An industrial hardware campaign landing page built in Webflow, using a dark visual system and scanning-inspired motifs.', tools: 'Webflow · Campaign landing page · Visual system' }
];
