/* Edit project copy, images and video URLs here. Paths are relative for GitHub Pages.
   Videos load only when opened in dialog. */
window.PORTFOLIO_PROJECTS = [
  {
    id: 'tavus',
    title: 'Tavus AI Avatars',
    category: '3D & Generative AI Commercial',
    filters: ['3d', 'motion', 'ai'],
    image: 'assets/project-tavus-ai.jpg',
    alt: 'Tavus AI realistic avatar generation commercial',
    description: 'High-concept 3D technology demo and promotional commercial showcasing Tavus\'s AI avatar replication engine, digital human simulation, and interactive video generation.',
    tools: 'Blender 3D · Generative AI Video · Commercial Direction · Premiere Pro · Motion Graphics',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/tavus-ai-avatars.mp4',
    external: 'https://www.playbook.com/s/macstorage/HMVvXiJQAEXhbsBTuyTb444V?assetToken=GKvPumJRUjGQSsUcDXHc8anZ',
    selected: true
  },
  {
    id: 'epson-fashion',
    title: 'Epson — AI Fashion Film',
    category: 'AI-Generated Fashion Film Commercial',
    filters: ['ai', 'motion', 'graphic'],
    image: 'assets/project-epson.jpg',
    alt: 'Epson AI-generated fashion commercial trilogy',
    description: 'An avant-garde AI-generated commercial fashion film combining Google Veo, Kling AI generation, dynamic editorial pacing, and cinematic sound design.',
    tools: 'Google Veo · Kling AI · Commercial Film Direction · Premiere Pro · Motion Graphics',
    video: 'https://my-portfolio-e4rk.vercel.app/epson-ai-video-web.mp4',
    external: 'https://www.playbook.com/s/macstorage/ecwWKDUyikQnv79PNcgqdMRE?assetToken=RjVYxKqek9Anv3CW6pkyuT6G',
    selected: true
  },
  {
    id: 'entrust',
    title: 'Entrust — AI Technology Film',
    category: 'AI Generation & Commercial Video',
    filters: ['ai', 'motion'],
    image: 'assets/project-entrust.jpg',
    alt: 'Entrust AI commercial video film',
    description: 'Cinematic widescreen AI video and motion direction exploring high-tech digital security and automated identity systems through stylized generative visuals.',
    tools: 'Generative AI Video · Kling AI · After Effects · Premiere Pro · Sound Design',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/entrust.mp4',
    external: 'https://www.playbook.com/s/macstorage/ywkwvRFD1EgtPfzP8ZqKaQss?assetToken=Av9PbnaD2ftgMv8WqYCqQnRH',
    selected: true
  },
  {
    id: 'folad',
    title: 'Folad — Circular Lifecycle',
    category: 'Industrial Lifecycle & Motion Graphic',
    filters: ['motion', 'graphic'],
    image: 'assets/project-folad.jpg',
    alt: 'Folad industrial circular economy lifecycle motion graphic',
    description: 'Visualizes the industrial product life cycle as a continuous, looping journey from consumption to production and recycling, crafted in a fluid motion graphic narrative.',
    tools: '2D Motion Graphics · Vector Illustration · After Effects · Storyboarding',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/folad-lifecycle.mp4',
    external: 'https://www.playbook.com/s/macstorage/pYaXXpBj5YnkrA8aumdEgbco?assetToken=7q8iMjutFBM7yu6NDsNf1b99',
    selected: true
  },
  {
    id: 'ussteel',
    title: 'US Steel — Infographic Presentation',
    category: 'Infographic & Corporate Motion Graphics',
    filters: ['graphic', 'motion'],
    image: 'assets/project-us-steel.jpg',
    alt: 'US Steel corporate infographic motion graphics presentation',
    description: 'An infographic-based motion graphic presentation designed to communicate key organizational capabilities, strategic data points, and operational insights during executive meetings.',
    tools: 'After Effects · Data Visualization · Infographic Motion Design · Illustrator',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/us-steel-infographic.mp4',
    external: 'https://www.playbook.com/s/macstorage/TBQGY4xR5iWQQeUi48VwuNEd?assetToken=inzrNavbkGrTb4PAMPvkq2U2',
    selected: true
  },
  {
    id: 'azki',
    title: 'Azki — Brand Commercial',
    category: 'Commercial / Motion Graphics',
    filters: ['motion', 'graphic'],
    image: 'assets/project-azki.jpg',
    alt: 'Azki commercial motion graphics campaign',
    description: 'High-impact brand motion campaign and commercial storytelling featuring vibrant typography, dynamic pacing, and clean visual identity design.',
    tools: 'After Effects · Motion Design · Premiere Pro · Sound Design',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/azki.mp4',
    external: 'https://www.playbook.com/s/macstorage/i2kCvUAbjZHZPFzvUGuYLMxx?assetToken=SZ6T76sqyA4LbT1zvUCsRith',
    selected: true
  },
  {
    id: 'pixel',
    title: 'Pixel Network',
    category: 'Campaign visuals / Motion graphics',
    filters: ['graphic', 'motion'],
    image: 'assets/project-pixel-network.jpg',
    alt: 'Colourful vector illustration of a driver in a landscape',
    description: 'A social motion campaign built around colourful vector illustration and kinetic typography. A visual identity carried through short, engaging animated stories.',
    tools: 'After Effects · Vector motion graphics · Kinetic typography',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/pixel-network.mp4',
    external: 'https://www.playbook.com/s/macstorage/nNaouTCFLEnKxkHvocNfR3A1?assetToken=Q3hydrZgSK8FouiTb5JkaydJ',
    selected: true
  },
  {
    id: 'nestle',
    title: 'Nestle — a little energy',
    category: 'Commercial / Motion graphics',
    filters: ['graphic', 'motion'],
    image: 'assets/project-nestle.jpg',
    alt: 'Colourful illustrated food icons on a bright yellow background',
    description: 'A short commercial motion piece combining playful illustrated visuals, rhythmic editing, and sound design.',
    tools: 'After Effects · Premiere Pro · Motion design · Sound design',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/nestle-motion.mp4',
    external: 'https://www.playbook.com/s/macstorage/xWwoCnQA7PLfvsk6nceexhqP?assetToken=cucgyqr7SMfYf4mxAZEetDzR',
    selected: true
  },
  {
    id: 'subify',
    title: 'Subify — simply explained',
    category: '2D & 3D / Explainer',
    filters: ['motion', '3d'],
    image: 'assets/project-subify.jpg',
    alt: 'Your Shop illustration from the Subify explainer',
    description: 'An animated product explainer that uses simple forms and bold colour to make application features and workflows easier to understand.',
    tools: 'After Effects · Figma · 2D motion graphics · 3D animation · Sound design',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/subify-explainer.mp4',
    external: 'https://www.playbook.com/s/macstorage/R1CDtjFBi7EbCHPJXsduirhx?assetToken=UhzFTS63qnWGaCk9WDoe1Rmg',
    selected: true
  },
  {
    id: 'epson',
    title: 'Epson C8000',
    category: '3D modelling / Product animation',
    filters: ['3d'],
    image: 'assets/project-blender-c8000.png',
    alt: 'Close-up 3D render of an Epson C8000 printer',
    description: 'Hard-surface product modelling and animation in Blender, with studio lighting and detailed texturing to reveal the product’s form.',
    tools: 'Blender · Hard-surface modelling · Lighting · Texturing · Product animation',
    video: 'https://my-portfolio-e4rk.vercel.app/c8000u-web.mp4',
    external: 'https://www.playbook.com/s/macstorage/AAKgAAByJUrAN91dNWTw7aJH?assetToken=fEAqdcVwg8hMYYG3RWyR8bin',
    selected: true
  },
  {
    id: 'bauer',
    title: 'Bauer Vapor',
    category: '3D modelling / Product animation',
    filters: ['3d'],
    image: 'assets/project-bauer-skate.png',
    alt: 'Bauer Vapor inline skate rendered inside an arena',
    description: 'A 3D exploration of the Bauer Vapor inline skate. Detailed hard-surface modelling, layered materials, and arena lighting bring the product into focus.',
    tools: 'Blender · Hard-surface modelling · Shading · Product animation',
    video: 'https://my-portfolio-e4rk.vercel.app/skate-3d-animation-web.mp4',
    external: 'https://www.playbook.com/s/macstorage/vZhygRYsf2ip8xfv5QnpKUKp?assetToken=PQL7EUXa3esyMCS7GdASv924',
    selected: true
  },
  {
    id: 'honeywell',
    title: 'Print Without Limits',
    category: 'Campaign creative / Digital design',
    filters: ['graphic'],
    image: 'assets/project-honeywell.png',
    alt: 'Honeywell Print Without Limits campaign on a desktop monitor',
    description: 'Campaign creative and a Webflow landing page for Honeywell. Hardware mockups, digital ads, and a cohesive visual direction bring the product campaign together.',
    tools: 'Webflow · Campaign creative · Hardware mockups · Digital ads',
    selected: true
  },
  {
    id: 'zebra',
    title: 'Zebra Technologies',
    category: 'Campaign & Web Design',
    filters: ['graphic'],
    image: 'assets/zebra-page.webp',
    alt: 'Full Zebra industrial hardware campaign landing page',
    description: 'An industrial hardware campaign landing page built in Webflow, using a dark visual system and scanning-inspired motifs.',
    tools: 'Webflow · Campaign landing page · Visual system',
    selected: true
  },
  {
    id: 'reel',
    title: '3D product animation showreel',
    category: 'Selected motion / 01:15',
    filters: ['3d', 'motion'],
    image: 'assets/project-reel-3d.jpg',
    alt: '3D product animation showreel frame',
    description: 'A collection of 3D product animations, studio lighting, hard-surface modelling, and commercial product demonstrations.',
    tools: 'Blender · Cinema 4D · After Effects · Studio lighting',
    video: 'https://my-portfolio-e4rk.vercel.app/videos/reel-3d-product.mp4',
    external: 'https://www.playbook.com/s/macstorage/v5o557yrHNYKFSbEcqKWSXV1?assetToken=Z9pDifP7BXiA4rvQ6qeyTCEm'
  }
];
